#!/bin/bash
# Install and initialize
pip install -r requirements.txt
if ! [ -r .config ]; then
  cat >.config <<EOF
mp3 = FALSE
directory = MUSIC_FOLDER
token = DISCOGS_TOKEN
username = MUSICBRAINZ_USERNAME
password = MUSICBRAINZ_PASSWORD
EOF
  echo "Created default configuration file '${0%/*}/.config'."
fi
